//! L4 differential: our peak consensus vs upstream's own `RACollection`.
//!
//! `crates/macs-callvar/tests/data/callvar_peak_refseq.golden` is generated by
//! `oracle/dump_callvar_refseq.py`, which builds a `RACollection` per peak inside the
//! pinned oracle and records `left`, `right`, `RAs_left`, `RAs_right`, the read counts,
//! and **both** `peak_refseq_ext` and the `peak_refseq` slice of it.
//!
//! This is the check that made `--fermi off` exact, and it is worth keeping separate
//! from the VCF comparison for a specific reason: `callvar` has no genome, so the peak
//! reference is a **consensus built from the reads**. Getting one byte of it wrong
//! shifts every reference base after it, and the symptom is a VCF that is wrong
//! *everywhere* rather than at one peak. Comparing the consensus directly localises
//! such a bug to a peak and a field; comparing VCFs cannot.
//!
//! `count_T`/`count_C` are deliberately excluded: this dump applies
//! `remove_outliers` on our side, and the consensus is built *before* that step, so the
//! counts legitimately differ by the number of outliers removed.
//!
//! The oracle's own BAMs come from the pinned checkout, which is located through the
//! environment and is not vendored, so the test skips (loudly, on stderr) where there
//! is none. See `tests/oracle/mod.rs`.

use macs_callvar::ra_collection_dump::{dump_peak_records, DumpOptions};

mod oracle;

const GOLDEN: &str = "tests/data/callvar_peak_refseq.golden";

struct GoldenPeak {
    chrom: String,
    left: i64,
    right: i64,
    ras_left: i64,
    ras_right: i64,
    ext_len: usize,
    seq_hex: String,
    ext_hex: String,
}

fn golden() -> Vec<GoldenPeak> {
    let text = std::fs::read_to_string(GOLDEN)
        .unwrap_or_else(|e| panic!("{GOLDEN} missing ({e}); run oracle/dump_callvar_refseq.py"));
    let mut v = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        assert_eq!(f.len(), 10, "unexpected golden shape: {line}");
        v.push(GoldenPeak {
            chrom: f[0].to_string(),
            left: f[1].parse().unwrap(),
            right: f[2].parse().unwrap(),
            ras_left: f[3].parse().unwrap(),
            ras_right: f[4].parse().unwrap(),
            ext_len: f[7].parse().unwrap(),
            seq_hex: f[8].to_string(),
            ext_hex: f[9].to_string(),
        });
    }
    v
}

#[test]
fn peak_consensus_is_byte_identical_to_the_oracle() {
    // Upstream's own test data is read out of the pinned tree, so no BAM is
    // committed here and the fixture cannot drift from the oracle's.
    let Some(oracle) = oracle::require("peak_consensus_is_byte_identical_to_the_oracle") else {
        return;
    };
    let test_dir = oracle.test_dir();
    let peaks_file = test_dir.join("callvar_testing.narrowPeak");
    let tbam = test_dir.join("CTCF_PE_ChIP_chr22_50k.bam");
    let cbam = test_dir.join("CTCF_PE_CTRL_chr22_50k.bam");
    for p in [&peaks_file, &tbam, &cbam] {
        assert!(
            p.exists(),
            "{} missing -- the oracle tree is incomplete for this differential",
            p.display()
        );
    }

    let g = golden();
    assert_eq!(g.len(), 10, "upstream's fixture has 10 read-covered peaks");

    let ours = dump_peak_records(&DumpOptions {
        peaks: &peaks_file,
        tbam: &tbam,
        cbam: Some(&cbam),
        max_duplicate: 1,
    })
    .expect("dump_peak_records");
    assert_eq!(ours.len(), g.len(), "peak count must match the oracle");

    for (want, got) in g.iter().zip(&ours) {
        let chrom = String::from_utf8_lossy(&got.chrom).into_owned();
        assert_eq!(chrom, want.chrom, "peak order must match (sorted by coord)");
        assert_eq!(got.left, want.left, "{chrom}: peak left");
        assert_eq!(got.right, want.right, "{chrom}: peak right");
        assert_eq!(got.read_start, want.ras_left, "{chrom}: RAs_left");
        assert_eq!(got.read_end, want.ras_right, "{chrom}: RAs_right");
        assert_eq!(got.ext_len, want.ext_len, "{chrom}: peak_refseq_ext length");

        // The extended buffer, byte for byte. This is the one that carries the
        // Python `bytearray` slice-assignment resize, so a divergence here shifts
        // everything downstream.
        assert_eq!(
            got.ext_hex, want.ext_hex,
            "{chrom} @{}: peak_refseq_ext differs",
            want.left
        );
        assert_eq!(
            got.seq_hex, want.seq_hex,
            "{chrom} @{}: peak_refseq differs",
            want.left
        );
    }
}

#[test]
fn the_two_byte_identical_peaks_stay_distinct() {
    // The fixture contains `peak_7a` and `peak_7b` at the same coordinates, which is
    // why upstream's VCF has 22 records over 13 distinct positions. The dump must keep
    // both -- deduplicating here would silently hide the duplicate-record behaviour.
    let text = std::fs::read_to_string(GOLDEN).unwrap();
    let starts: Vec<&str> = text
        .lines()
        .filter(|l| !l.starts_with('#') && !l.trim().is_empty())
        .map(|l| l.split('\t').nth(1).unwrap())
        .collect();
    let mut sorted = starts.clone();
    sorted.sort_unstable();
    let dups = sorted.windows(2).filter(|w| w[0] == w[1]).count();
    assert_eq!(dups, 1, "one coordinate appears twice in the peak fixture");
    assert_eq!(starts.len(), 10);
}
