//! L4 golden: `macs_callvar::variant_stat` vs the pinned oracle's compiled
//! `VariantStat` extension.
//!
//! `tests/data/variant_stat.golden` is generated by `oracle/check_variant_stat.py`,
//! which drives the installed `.so` at `oracle/ENV.lock`'s pinned MACS3 3.0.5 and
//! records the inputs alongside the answers. It covers 410 cases, including every
//! branch the implementation has:
//!
//! * both samples empty, control-only, treatment-only;
//! * `tn == 1` (a single read takes its own path in both greedy searches);
//! * `m == 0` and `m == tn` (no read / every read carries the top1 base);
//! * base qualities at both extremes (`0` and `93`, Phred's cap);
//! * the `GreedyMaxFunctionAS` sweep running in both directions, so the `1e-8`
//!   stopping rule is exercised rather than merely executed.
//!
//! # Why this is bit-exact and not tolerance-based
//!
//! These functions accumulate `f64` log-likelihoods in a fixed order over loops whose
//! lengths are the read counts. A `f64` implementation that reassociates those sums --
//! a pairwise sum, a vectorised reduction, `fma` -- differs in the last bits. That
//! difference would not change any peak this feeds, but it would change `GQ` after the
//! C `(int)` truncation, which is a value written into a VCF. So the floats are
//! compared with `to_bits()` equality and the `.17g` text is parsed losslessly.
//!
//! The one thing compared loosely is the error path: upstream raises a Python
//! `Exception` for an empty treatment and we return `Err`, so the golden records
//! `ERR` and the test asserts only that both sides failed.

use macs_callvar::{
    cal_model_heter_as, cal_model_heter_noas, cal_model_homo, calculate_gq,
    calculate_gq_heter_assig, DEFAULT_MAX_ALLOWED_AR,
};
use std::path::Path;

const GOLDEN: &str = "tests/data/variant_stat.golden";

fn parse_bq(field: &str) -> Vec<i32> {
    if field.is_empty() {
        return Vec::new();
    }
    field
        .split(',')
        .map(|x| x.parse::<i32>().expect("base qualities are integers"))
        .collect()
}

/// Lossless `f64` parse, so the comparison is on bits rather than on text.
fn parse_f(s: &str) -> Option<f64> {
    s.parse::<f64>().ok()
}

struct Row<'a> {
    name: &'a str,
    top1_t: Vec<i32>,
    top1_c: Vec<i32>,
    top2_t: Vec<i32>,
    top2_c: Vec<i32>,
    // (label, oracle text)
    floats: Vec<(&'a str, &'a str)>,
    ints: Vec<(&'a str, i32)>,
}

fn read_rows<'a>(text: &'a str) -> Vec<Row<'a>> {
    let mut rows = Vec::new();
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        assert!(f.len() >= 19, "short row in {GOLDEN}: {line}");
        rows.push(Row {
            name: f[0],
            top1_t: parse_bq(f[1]),
            top1_c: parse_bq(f[2]),
            top2_t: parse_bq(f[3]),
            top2_c: parse_bq(f[4]),
            floats: vec![
                ("homo_lnL", f[5]),
                ("homo_BIC", f[6]),
                ("noas_lnL", f[7]),
                ("noas_BIC", f[8]),
                ("as_lnL", f[9]),
                ("as_BIC", f[10]),
            ],
            ints: vec![
                ("gq12", f[11].parse().unwrap()),
                ("gq_eq", f[12].parse().unwrap()),
                ("gq_far", f[13].parse().unwrap()),
                ("gq_near", f[14].parse().unwrap()),
                ("assig12", f[15].parse().unwrap()),
                ("assig_eq", f[16].parse().unwrap()),
                ("assig_far", f[17].parse().unwrap()),
                ("assig_near", f[18].parse().unwrap()),
            ],
        });
    }
    assert!(
        rows.len() >= 400,
        "expected the full corpus, got {}",
        rows.len()
    );
    rows
}

#[test]
fn variant_stat_matches_the_pinned_oracle_bit_for_bit() {
    if !Path::new(GOLDEN).exists() {
        panic!("{GOLDEN} missing; run oracle/check_variant_stat.py");
    }
    let text =
        std::fs::read_to_string(GOLDEN).unwrap_or_else(|e| panic!("{GOLDEN} unreadable: {e}"));
    let mut checked_floats = 0usize;
    let mut checked_ints = 0usize;
    let mut err_rows = 0usize;

    for row in read_rows(&text) {
        let (t1, c1) = (&row.top1_t, &row.top1_c);
        let (t2, c2) = (&row.top2_t, &row.top2_c);

        let mut compare = |label: &str, ours: Result<(f64, f64), String>, want: (&str, &str)| {
            let (w_l, w_b) = (parse_f(want.0), parse_f(want.1));
            if w_l.is_none() || w_b.is_none() {
                assert!(
                    ours.is_err(),
                    "{}: oracle raised for {} but ours returned {:?}",
                    row.name,
                    label,
                    ours
                );
                err_rows += 1;
                return;
            }
            let (l, b) = ours.unwrap_or_else(|e| {
                panic!(
                    "{}: oracle succeeded for {} but ours errored: {e}",
                    row.name, label
                )
            });
            let (wl, wb) = (w_l.unwrap(), w_b.unwrap());
            assert_eq!(
                l.to_bits(),
                wl.to_bits(),
                "{} {label}: lnL {l:.17} vs oracle {wl:.17} (ulp differs)",
                row.name
            );
            assert_eq!(
                b.to_bits(),
                wb.to_bits(),
                "{} {label}: BIC {b:.17} vs oracle {wb:.17} (ulp differs)",
                row.name
            );
            checked_floats += 2;
        };

        compare(
            "homo",
            cal_model_homo(t1, c1, t2, c2),
            (row.floats[0].1, row.floats[1].1),
        );
        compare(
            "heter_noas",
            cal_model_heter_noas(t1, c1, t2, c2),
            (row.floats[2].1, row.floats[3].1),
        );
        compare(
            "heter_as",
            cal_model_heter_as(t1, c1, t2, c2, DEFAULT_MAX_ALLOWED_AR),
            (row.floats[4].1, row.floats[5].1),
        );

        // GQ: same four likelihood triples the oracle used, so a change of probe
        // values cannot quietly turn this into a self-consistent test.
        let triples = [
            (-1.0f64, -2.0f64, -3.0f64),
            (-5.0, -5.0, -5.0),
            (-1.0, -80.0, -160.0),
            (-0.001, -0.002, -0.0005),
        ];
        for (i, (a, b, c)) in triples.iter().enumerate() {
            let got = calculate_gq(*a, *b, *c);
            let (label, want) = row.ints[i];
            assert_eq!(
                got, want,
                "{} {label}: GQ({a}, {b}, {c}) = {got}, oracle {want}",
                row.name
            );
            checked_ints += 1;
        }

        let pairs = [
            (-1.0f64, -2.0f64),
            (-5.0, -5.0),
            (-1.0, -90.0),
            (-0.001, -0.002),
        ];
        for (i, (a, b)) in pairs.iter().enumerate() {
            let got = calculate_gq_heter_assig(*a, *b);
            let (label, want) = row.ints[4 + i];
            assert_eq!(
                got, want,
                "{} {label}: ASsig({a}, {b}) = {got}, oracle {want}",
                row.name
            );
            checked_ints += 1;
        }
    }

    // Count what the file *should* have produced, so a field that silently stopped
    // being compared fails here instead of passing on a smaller total.
    let mut want_floats = 0usize;
    let mut want_err = 0usize;
    for line in text.lines() {
        if line.starts_with('#') || line.trim().is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        for col in (5..11).step_by(2) {
            if f[col] == "ERR" {
                want_err += 1;
            } else {
                want_floats += 2;
            }
        }
    }
    assert_eq!(
        checked_floats, want_floats,
        "compared a different number of floats than the golden holds"
    );
    assert_eq!(
        err_rows, want_err,
        "error rows must line up with the golden"
    );
    assert_eq!(
        checked_ints,
        410 * 8,
        "the 8 GQ/ASsig fields never fail, so all of them must be compared"
    );
    assert!(
        err_rows > 0,
        "the corpus must include the empty-treatment error path"
    );
}

#[test]
fn gq_is_not_clamped_by_upstream_and_nor_by_us() {
    // `gq_far` is 343 and `assig_far` is 386 in the golden: upstream's `(int)` cast
    // happily exceeds 255. Clamping to the VCF's 0-255 range would be an improvement,
    // and it would be a compatibility break, so neither side clamps.
    assert_eq!(calculate_gq(-1.0, -80.0, -160.0), 343);
    assert_eq!(calculate_gq_heter_assig(-1.0, -90.0), 386);
}
