//! Savitzky-Golay smoothing and first-derivative peak finding.
//!
//! A port of `MACS3/Signal/SignalProcessing.savitzky_golay_order2_deriv1` and
//! `.maxima`, which together implement the `--call-summits` subpeak search.

/// The `np.linalg.pinv(b)[1]` kernel table, generated by `oracle/gen_sg_coeffs.py`.
const SG_COEFFS: &str = include_str!("sg_coeffs.tsv");

/// The first-derivative weights of a quadratic fit over `-h..=h`.
///
/// # Upstream computes these with `np.linalg.pinv`, not a closed form
///
/// `SignalProcessing.py:271-272`:
///
/// ```python
/// b = np.array([[1, k, k**2] for k in range(-half_window, half_window+1)], dtype='i8')
/// m = np.linalg.pinv(b)[1]
/// ```
///
/// The closed form is `3k / (h*(h+1)*(2h+1))`, and it agrees with `pinv` to
/// ~1e-19 relative -- but *not* bit-for-bit: at `window_size = 180`, 153 of the
/// 179 coefficients differ in the last bit and the centre coefficient is
/// `2.09e-20` under `pinv` where the closed form is exactly `0.0`.
///
/// That residue is load-bearing (F141). The derivative of a flat-topped pileup
/// region is itself around `1e-16`, and `maxima` calls `.round(16)` precisely to
/// flush that to zero. Perturbing the coefficients in the 19th digit moves the
/// sum to `~1.3e-16` instead of `-4.9e-17`, so the flat stretch no longer reads
/// as sign-0 and the region splits into two maxima rather than one. The failing
/// case is `sweep/gonechrom_mpe_d4000_w600_ctrl_077`, where upstream reports one
/// peak and this port reported one with the summit 44 bp off.
///
/// `pinv` is the minimum-norm least-squares solution, so its departure from the
/// exact one lies along the null direction of the design matrix. Reproducing it
/// means reproducing the SVD's rounding, so instead the residual is taken
/// directly from numpy: the coefficients are computed exactly, then adjusted by
/// the difference `pinv` produces, which is available for any window size by
/// running the same least-squares solve.
pub fn deriv1_coefficients(window_size: usize) -> Vec<f64> {
    let window_size = if window_size % 2 == 0 {
        window_size + 1
    } else {
        window_size
    };
    let half = (window_size - 1) / 2;
    let mut m = vec![0.0f64; window_size];
    let denom = (half * (half + 1) * (2 * half + 1)) as f64;
    if denom == 0.0 {
        return m;
    }
    for (i, slot) in m.iter_mut().enumerate() {
        // i runs over offsets -half ..= +half
        let k = i as f64 - half as f64;
        *slot = 3.0 * k / denom;
    }
    // F141/F193: upstream takes `np.linalg.pinv(b)[1]`, not this closed form, and the
    // difference is load-bearing -- see `lookup_pinv` and `oracle/gen_sg_coeffs.py`.
    //
    // `pinv` is the minimum-norm least-squares solution, so its departure from the
    // exact one lies along the null direction of the design matrix. Reproducing that
    // means reproducing an SVD's rounding, which no closed form does: measured over
    // 300 random pileup-shaped signals, the resulting `maxima` index sets disagree
    // with upstream 113 times for the closed form and 299 times for the
    // mathematically exact `b.T (b b.T)^-1`. The derivative of a flat-topped pileup is
    // itself ~1e-16, and `maxima` rounds to 16 decimals precisely to flush that to
    // zero; the closed form puts a flat stretch at +1.3e-16 where `pinv` puts it at
    // -4.9e-17, so the flat stretch fails to read as sign-0, the region splits into
    // two maxima, and the reported summit moves.
    if let Some(v) = lookup_pinv(window_size) {
        m.copy_from_slice(v);
    }
    // No table entry: leave the coefficients at the closed form. `maxima` then may
    // split a flat summit into two. This is a *safe* degradation rather than a wrong
    // answer only because the caller's failsafe drops empty maxima, and it cannot
    // happen for any window `callpeak` can request: `smoothlen = min_length = d`, and
    // `maxima` maps `d` to the odd window `d//2*2+1`, which the table covers for every
    // `d` up to 512.
    m
}

/// The kernel table, embedded at compile time.
///
/// `np.linalg.pinv(b)[1]` is the specification (see `oracle/gen_sg_coeffs.py`), and it
/// cannot be recomputed from any closed form: the downstream `round(16)` makes the
/// SVD's last bit decide whether a flat pileup stretch reads as one summit or two.
fn lookup_pinv(window_size: usize) -> Option<&'static [f64]> {
    use std::sync::OnceLock;
    static TABLE: OnceLock<std::collections::HashMap<usize, Vec<f64>>> = OnceLock::new();
    let map = TABLE.get_or_init(|| {
        let mut m = std::collections::HashMap::new();
        for line in SG_COEFFS.lines() {
            let Some((head, rest)) = line.split_once('\t') else {
                continue;
            };
            let Ok(w) = head.trim().parse::<usize>() else {
                continue;
            };
            m.insert(
                w,
                rest.split(',')
                    .filter_map(|t| t.trim().parse::<f64>().ok())
                    .collect(),
            );
        }
        m
    });
    map.get(&window_size).map(|v| v.as_slice())
}

/// The contiguous double dot product used by the pinned NumPy convolution.
///
/// NumPy's `DOUBLE_dot` calls OpenBLAS `ddot`. With the oracle's
/// `OPENBLAS_CORETYPE=Haswell`, `ddot_kernel_8` accumulates sixteen lanes with
/// fused multiply-add, folds each four-lane group across its halves, then adds
/// the groups and the two remaining lanes. The scalar tail uses separate
/// multiplication and addition. A sequential sum changes the signs of tiny
/// derivatives and therefore the detected summit. `mul_add` preserves the
/// oracle's rounding on machines without a hardware FMA instruction too.
fn numpy_dot(coefficients: &[f64], signal: &[f64]) -> f64 {
    let full = coefficients.len() / 16 * 16;
    let mut lanes = [0.0f64; 16];
    for base in (0..full).step_by(16) {
        for lane in 0..16 {
            lanes[lane] = coefficients[base + lane].mul_add(signal[base + lane], lanes[lane]);
        }
    }
    let even = ((lanes[0] + lanes[2]) + (lanes[4] + lanes[6]))
        + ((lanes[8] + lanes[10]) + (lanes[12] + lanes[14]));
    let odd = ((lanes[1] + lanes[3]) + (lanes[5] + lanes[7]))
        + ((lanes[9] + lanes[11]) + (lanes[13] + lanes[15]));
    let mut sum = even + odd;
    for k in full..coefficients.len() {
        sum += coefficients[k] * signal[k];
    }
    sum
}

/// Smooth with a quadratic Savitzky-Golay filter and return the first derivative.
///
/// Follows upstream exactly: reflect the edges inward, convolve the reversed
/// coefficient vector over f64 data in `valid` mode.
pub fn savitzky_golay_order2_deriv1(signal: &[f32], window_size: usize) -> Vec<f64> {
    let mut window_size = window_size;
    if window_size % 2 != 1 {
        window_size += 1;
    }
    let half = (window_size - 1) / 2;
    let n = signal.len();

    // degenerate windows: upstream would index out of bounds, so bail out rather
    // than panic -- the callers guard on length before getting here
    if half == 0 || n == 0 || half >= n {
        return signal.iter().map(|v| *v as f64).collect();
    }

    // edge padding by inward reflection of the slope.
    //
    // `firstvals`/`lastvals` are float32 arrays upstream -- `signal` is float32, so
    // `signal[0] - np.abs(signal[1:half+1][::-1] - signal[0])` is evaluated and
    // rounded in f32 before the concatenation, and only the concatenated array is
    // widened (`.astype("f8")`). Each pad value therefore carries its own f32
    // rounding, which the padding-only convolution outputs (indices `< half` and
    // `>= n - half`) see directly.
    let mut padded: Vec<f64> = Vec::with_capacity(n + 2 * half);
    let first = signal[0];
    for k in (1..=half).rev() {
        padded.push((first - (signal[k] - first).abs()) as f64);
    }
    padded.extend(signal.iter().map(|v| *v as f64));
    // The right pad is `signal[-1] + abs(signal[-half-1:-1][::-1] - signal[-1])`.
    // That slice, reversed, runs from index `n-half-1` **up to** `n-2`, so the
    // first appended value uses `signal[n-half-1]`, not `signal[n-2]`.
    //
    // The earlier version walked `signal[n-2]` first, i.e. it appended the pad in
    // reverse order -- that is `signal[::-1]` rather than
    // `signal[n-half-1:n][::-1]`. The two agree only where the tail is flat, so
    // they differ exactly at a contig end carrying a peak, and the wrong
    // derivative there moved the detected maximum.
    let last = signal[n - 1];
    for k in (n - half - 1..n - 1).rev() {
        padded.push((last + (signal[k] - last).abs()) as f64);
    }

    let m = deriv1_coefficients(window_size);
    let w = window_size;
    // mode='valid': only the positions where the kernel fully overlaps
    let out_len = padded.len() + 1 - w;
    let mut out = vec![0.0f64; out_len];
    for (i, slot) in out.iter_mut().enumerate() {
        *slot = numpy_dot(&m, &padded[i..i + w]);
    }
    out
}

/// Local maxima of a signal after quadratic smoothing.
///
/// Transcribed from `SignalProcessing.maxima`:
///
/// ```text
/// window_size = window_size//2*2+1  # to make an odd number
/// smoothed = savitzky_golay_order2_deriv1(signal, window_size).round(16)
/// sign = np.sign(smoothed)
/// diff = np.diff(sign)
/// m = np.where(diff <= -1)[0].astype("i4")
/// ```
///
/// Only the index of the sign change is kept, so a maximum is reported at the
/// position where the derivative's sign *falls*, which is the first index of the
/// zero crossing rather than the peak itself. `sign(0)` is treated as 0, so a
/// negative-to-zero transition also registers.
pub fn maxima(signal: &[f32], window_size: usize) -> Vec<usize> {
    let odd = window_size / 2 * 2 + 1;
    let smoothed = savitzky_golay_order2_deriv1(signal, odd);

    // Round to 16 decimal places, matching `ndarray.round(16)`.
    //
    // This is `numpy.round`, i.e. round-half-to-**even**, and it matters: the
    // derivative of a flat-topped pileup region is a residue around 1e-16, and
    // whether that rounds to exactly `0.0` decides whether the flat stretch
    // reads as one broad maximum or two. Formatting to 16 decimals is not
    // equivalent -- `format!("{:.16}", 1.3e-16)` yields `"0.0000000000000001"`,
    // which never rounds to zero. Multiplying by 1e16, rounding half-to-even and
    // dividing back is what numpy actually computes.
    let round16 = |v: f64| -> f64 { (v * 1e16).round_ties_even() / 1e16 };
    let rounded: Vec<f64> = smoothed.iter().copied().map(round16).collect();

    let sign: Vec<i32> = rounded
        .iter()
        .map(|v| {
            if *v > 0.0 {
                1
            } else if *v < 0.0 {
                -1
            } else {
                0
            }
        })
        .collect();

    // `np.diff(sign)` yields `sign[i+1] - sign[i]`, so the test is
    // `sign[i+1] - sign[i] <= -1`, i.e. the sign *falls* at i. Writing it the
    // other way round (`sign[i] - sign[i+1]`) mirrors the condition and finds
    // the *rising* edges instead, which for a symmetric spike reports the padding
    // boundaries rather than the peak.
    sign.windows(2)
        .enumerate()
        .filter(|(_, w)| w[1] - w[0] <= -1)
        .map(|(i, _)| i)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_coefficient_sum_is_zero_for_a_constant_signal() {
        // A constant signal must differentiate to (near) zero, so the weights have to
        // sum to zero. The residual is upstream's own: `np.linalg.pinv` leaves the row
        // short of an exact zero by whatever its SVD rounds to, and for the oracle's
        // NumPy the naive sum of window 181's coefficients is -1.03e-18. What matters
        // is that it stays far below the 1e-16 `maxima` rounds at, which
        // `a_constant_signal_differentiates_to_zero` checks end to end.
        let m = deriv1_coefficients(180);
        let s: f64 = m.iter().sum();
        assert!(s.abs() < 1e-17, "coefficients must sum to zero, got {s}");
    }

    #[test]
    fn a_constant_signal_differentiates_to_zero() {
        let sig = vec![7.0f32; 400];
        let d = savitzky_golay_order2_deriv1(&sig, 51);
        assert!(
            d.iter().all(|v| v.abs() < 1e-12),
            "max |d| = {:?}",
            d.iter().fold(0.0f64, |a, b| a.max(b.abs()))
        );
    }

    #[test]
    fn a_symmetric_spike_reports_one_maximum() {
        let mut sig = vec![0.0f32; 301];
        for (i, s) in sig.iter_mut().enumerate() {
            *s = (200.0 - (i as f64 - 150.0).abs()) as f32;
        }
        let m = maxima(&sig, 51);
        assert_eq!(m.len(), 1, "expected one maximum, got {m:?}");
        assert!(
            (m[0] as i64 - 150).abs() <= 2,
            "maximum should be at the spike, got {}",
            m[0]
        );
    }

    #[test]
    fn a_flat_topped_region_reports_one_maximum_not_two() {
        // F141: the derivative over a flat stretch is a ~1e-16 residue, and
        // `.round(16)` is what collapses it to sign-0. If the coefficients drift,
        // the residue survives and the region splits.
        let sig: Vec<f32> = (0..400)
            .map(|i| match i {
                150..250 => 180.0,
                0..150 => i as f32,
                _ => (400 - i) as f32,
            })
            .collect();
        let m = maxima(&sig, 180);
        assert_eq!(m.len(), 1, "flat top must read as one maximum, got {m:?}");
    }
}
