//! Bit-exact parity against the pinned MACS3 3.0.5 oracle.
//!
//! `tests/stats_vectors.tsv` is generated by
//! `oracle/gen_stats_vectors_real.py`, which calls the **compiled** Cython
//! extensions of MACS3 3.0.5 (`oracle/ENV.lock`) and records every result as
//! its exact IEEE-754 bit pattern. This test replays the same calls and requires
//! bit equality — no tolerance.
//!
//! Bit equality, not a tolerance, is the correct bar here. Upstream's log10
//! Poisson path is *systematically* wrong in the far tail
//! (`docs/upstream-findings.md` F1): `k = 30, lambda = 10` yields a p-score of
//! `7.09779` where the true value is `11.87413`. A tolerant test would happily
//! accept a correct implementation and quietly break compatibility. The only way
//! to be a drop-in replacement is to be wrong in exactly the same way.
//!
//! Regenerate with:
//!   /path/to/macs3-venv/bin/python oracle/gen_stats_vectors_real.py \
//!       > crates/macs-stats/tests/stats_vectors.tsv

use macs_stats::*;
use std::collections::BTreeMap;

/// A parsed golden row.
#[derive(Debug, Clone)]
struct Row {
    func: String,
    args: Vec<String>,
    expect: String,
}

fn load() -> Vec<Row> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/stats_vectors.tsv");
    let text = std::fs::read_to_string(path).unwrap_or_else(|e| {
        panic!("cannot read {path}: {e}; regenerate with oracle/gen_stats_vectors_real.py")
    });
    let mut out = Vec::new();
    for line in text.lines() {
        if line.trim().is_empty() {
            continue;
        }
        let mut fields: Vec<String> = line.split('\t').map(str::to_string).collect();
        // the last field is the expected value; everything between is arguments
        let expect = fields.pop().expect("expected value");
        let func = fields.remove(0);
        out.push(Row {
            func,
            args: fields,
            expect,
        });
    }
    assert!(out.len() > 4000, "only {} vectors loaded", out.len());
    out
}

fn bits64(v: f64) -> String {
    if v.is_nan() {
        "nan".to_string()
    } else if v == f64::INFINITY {
        "inf".to_string()
    } else if v == f64::NEG_INFINITY {
        "-inf".to_string()
    } else {
        format!("0x{:016x}", v.to_bits())
    }
}

fn af(s: &str) -> f64 {
    s.parse()
        .unwrap_or_else(|e| panic!("bad f64 arg {s:?}: {e}"))
}
fn au(s: &str) -> u64 {
    s.parse()
        .unwrap_or_else(|e| panic!("bad u64 arg {s:?}: {e}"))
}
fn ai(s: &str) -> i64 {
    s.parse()
        .unwrap_or_else(|e| panic!("bad i64 arg {s:?}: {e}"))
}

#[test]
fn bit_exact_parity_with_macs3() {
    let rows = load();
    let mut checked: BTreeMap<&str, usize> = BTreeMap::new();
    let mut failures: Vec<String> = Vec::new();
    let mut skipped = 0usize;

    for row in &rows {
        let a = &row.args;
        // Each arm produces the canonical string form of its result, so the
        // comparison is uniformly a string equality: f64/f32 as IEEE-754 bit
        // patterns, integers in decimal.
        let got: String = match row.func.as_str() {
            "poisson_cdf" => {
                let (k, lam, lower, log10) = (au(&a[0]), af(&a[1]), a[2] == "1", a[3] == "1");
                match poisson_cdf(k as u32, lam, lower, log10) {
                    Ok(v) => bits64(v),
                    Err(_) => {
                        skipped += 1;
                        continue;
                    }
                }
            }
            // the vector stores (lam, cdf, maximum); the upstream signature is
            // poisson_cdf_inv(cdf, lam, maximum)
            "poisson_cdf_inv" | "poisson_cdf_Q_inv" => {
                let v = poisson_cdf_inv(af(&a[1]), af(&a[0]), a[2].parse().unwrap())
                    .expect("upstream succeeded here");
                v.to_string()
            }
            "poisson_pdf" => bits64(poisson_pdf(au(&a[0]) as u32, af(&a[1]))),
            "binomial_pdf" => bits64(binomial_pdf(ai(&a[0]), ai(&a[1]), af(&a[2]))),
            "binomial_cdf_f" => bits64(binomial_cdf(ai(&a[0]), ai(&a[1]), af(&a[2]), true)),
            "binomial_cdf_r" => bits64(binomial_cdf(ai(&a[0]), ai(&a[1]), af(&a[2]), false)),
            "binomial_sf_f" => bits64(binomial_sf(ai(&a[0]), ai(&a[1]), af(&a[2]), true)),
            "binomial_sf_r" => bits64(binomial_sf(ai(&a[0]), ai(&a[1]), af(&a[2]), false)),
            "binomial_cdf_inv" => binomial_cdf_inv(af(&a[0]), ai(&a[1]), af(&a[2]))
                .expect("valid cdf")
                .to_string(),
            "pnorm" => bits64(pnorm(
                a[0].parse().unwrap(),
                a[1].parse().unwrap(),
                a[2].parse().unwrap(),
            )),
            // the oracle records `pnorm2` as f32 bits; the value itself is an
            // f64 computation truncated to `float32_t` (see macs_stats::pnorm2)
            "pnorm2" => format!(
                "0x{:08x}",
                pnorm2(
                    a[0].parse::<f32>().unwrap(),
                    a[1].parse::<f32>().unwrap(),
                    a[2].parse::<f32>().unwrap()
                )
                .to_bits()
            ),
            "pduplication" => {
                let n: i64 = ai(&a[0]);
                let p: f64 = af(&a[1]);
                // the oracle used pmf = [p, p, 2p, p]
                let pmf = [p, p, 2.0 * p, p];
                format!("0x{:08x}", pduplication(&pmf, n).to_bits())
            }
            "chisq_pvalue_e" => match chisq_pvalue_e(af(&a[0]), a[1].parse().unwrap()) {
                Ok(v) => bits64(v),
                Err(_) => {
                    skipped += 1;
                    continue;
                }
            },
            "chisq_logp_e" => match chisq_logp_e(af(&a[0]), a[1].parse().unwrap(), a[2] == "1") {
                Ok(v) => bits64(v),
                Err(_) => {
                    skipped += 1;
                    continue;
                }
            },
            "factorial" => bits64(factorial(au(&a[0]) as u32)),
            // documented upstream non-termination; see docs/upstream-findings.md F11
            "binomial_skipped" => {
                skipped += 1;
                continue;
            }
            other => {
                failures.push(format!("unhandled vector function {other:?}"));
                continue;
            }
        };
        *checked.entry(row.func.as_str()).or_default() += 1;
        if got != row.expect {
            failures.push(format!(
                "{}({}) got {got} want {}",
                row.func,
                a.join(", "),
                row.expect
            ));
        }
    }

    if !failures.is_empty() {
        let mut by_fn: BTreeMap<&str, usize> = BTreeMap::new();
        for f in &failures {
            let name = f.split('(').next().unwrap_or("?");
            *by_fn.entry(name).or_default() += 1;
        }
        eprintln!("failures by function: {by_fn:?}");
        panic!(
            "{} of {} golden vectors disagree with MACS3 3.0.5:\n{}",
            failures.len(),
            rows.len() - skipped,
            failures
                .iter()
                .take(40)
                .cloned()
                .collect::<Vec<_>>()
                .join("\n")
        );
    }

    // Every vectorised function must actually have been exercised, so a
    // silently renamed function cannot make this test vacuous.
    for required in [
        "poisson_cdf",
        "poisson_cdf_inv",
        "poisson_pdf",
        "binomial_pdf",
        "binomial_cdf_f",
        "binomial_cdf_r",
        "binomial_cdf_inv",
        "pnorm",
        "pnorm2",
        "chisq_pvalue_e",
        "pduplication",
    ] {
        assert!(
            checked.get(required).copied().unwrap_or(0) > 0,
            "no golden vectors were checked for {required}"
        );
    }
    eprintln!(
        "bit-exact parity: {} vectors OK ({} documented upstream skips)",
        checked.values().sum::<usize>(),
        skipped
    );
}

#[test]
fn oracle_lock_is_present() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../oracle/ENV.lock");
    let text =
        std::fs::read_to_string(path).unwrap_or_else(|e| panic!("oracle/ENV.lock missing: {e}"));
    assert!(
        text.contains("MACS3_VERSION=3.0.5"),
        "the golden vectors must come from MACS3 3.0.5, got:\n{text}"
    );
    assert!(
        text.contains("MACS3_PATH="),
        "ENV.lock must record the source tree"
    );
}

/// The oracle must be hermetic: the pinned working tree unmodified.
///
/// The porting plan's stage 1 requires a hermetic oracle, and an earlier phase
/// satisfied it only by instrumenting MACS3 in place. `oracle/dump_stages.py`
/// now observes the real pipeline from the outside, so the instrumentation is
/// gone. This test is the gate that keeps it gone: it runs the same check a
/// reviewer would, and fails loudly if the tree is re-dirtied.
#[test]
fn oracle_tree_is_unmodified() {
    let repo = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");
    let script = format!("{repo}/oracle/verify_oracle_clean.sh");
    assert!(
        std::path::Path::new(&script).exists(),
        "missing hermeticity check {script}"
    );
    let out = std::process::Command::new("bash")
        .arg(&script)
        .output()
        .expect("run verify_oracle_clean.sh");
    let stdout = String::from_utf8_lossy(&out.stdout);
    assert!(
        out.status.success(),
        "the pinned oracle is not hermetic:\n{stdout}\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(
        stdout.contains("no instrumentation hooks"),
        "unexpected output:\n{stdout}"
    );
}
