//! End-to-end test of the `macs3-rs callpeak` path: the derived flag parser ->
//! the shared library pipeline -> the three output files.
//!
//! This is the "Rust side" differential: it does not consult the oracle, but it
//! pins the CLI contract (a real invocation must produce `*.xls`,
//! `*.narrowPeak` and `*.summits.bed` with the expected shape) so a regression
//! in dispatch or in the flag->config mapping fails here rather than silently.

use macs_cli::{parse_flags, Options};

fn tmpdir(tag: &str) -> std::path::PathBuf {
    let d = std::env::temp_dir().join(format!("macs3rs-cli-{tag}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

/// Write a small, *realistic* fixture: two strong treatment clusters, with
/// control background spread genome-wide (as real MACS input is) but at much
/// lower density near the clusters, so every region has lambda > 0 and the fold
/// enrichment stays high enough to call peaks.
fn write_fixture(dir: &std::path::Path) -> (std::path::PathBuf, std::path::PathBuf) {
    let treat = dir.join("treat.bed");
    let ctrl = dir.join("ctrl.bed");
    let mut t = String::new();
    let mut c = String::new();
    // two strong treatment clusters
    for i in 0..40 {
        t.push_str(&format!("chr1\t{}\t{}\tr\t0\t+\n", 990 + i, 1000 + i));
        t.push_str(&format!("chr1\t{}\t{}\tr\t0\t-\n", 4990 + i, 5000 + i));
    }
    // control background: dense enough that lambda > 0 genome-wide, sparse at
    // the clusters so they stay enriched (2 reads per cluster vs 40 treatment)
    for i in 0..40 {
        c.push_str(&format!(
            "chr1\t{}\t{}\tr\t0\t+\n",
            20000 + i * 60,
            20060 + i * 60
        ));
    }
    c.push_str("chr1\t995\t1005\tr\t0\t+\n");
    c.push_str("chr1\t4995\t5005\tr\t0\t+\n");
    std::fs::write(&treat, t).unwrap();
    std::fs::write(&ctrl, c).unwrap();
    (treat, ctrl)
}

fn parse(args: &[&str]) -> Options {
    let argv: Vec<String> = args.iter().map(|s| s.to_string()).collect();
    parse_flags("callpeak", &argv).expect("callpeak args must parse")
}

#[test]
fn callpeak_writes_all_three_files_through_the_real_parser() {
    let dir = tmpdir("files");
    let (treat, ctrl) = write_fixture(&dir);
    let out = dir.join("out");
    let o = parse(&[
        "-t",
        treat.to_str().unwrap(),
        "-c",
        ctrl.to_str().unwrap(),
        "-f",
        "BED",
        "-g",
        "100000",
        "--nomodel",
        "--extsize",
        "200",
        "--outdir",
        out.to_str().unwrap(),
        "-n",
        "t1",
    ]);
    macs_cli::commands::callpeak::run(&o).expect("callpeak runs");

    let xls = std::fs::read_to_string(out.join("t1_peaks.xls")).expect("xls written");
    let np = std::fs::read_to_string(out.join("t1_peaks.narrowPeak")).expect("narrowPeak written");
    let sb = std::fs::read_to_string(out.join("t1_summits.bed")).expect("summits written");

    // XLS has the version banner and the column header
    assert!(
        xls.starts_with("# This file is generated by MACS version 3.0.5"),
        "xls banner"
    );
    assert!(xls.contains("abs_summit"), "xls header has abs_summit");
    // at least one data row on each output
    let xls_rows = xls
        .lines()
        .filter(|l| !l.starts_with('#') && !l.starts_with("chr\t"))
        .count();
    assert!(xls_rows >= 1, "at least one peak row, got {xls_rows}");
    assert!(!np.trim().is_empty(), "narrowPeak non-empty");
    assert!(!sb.trim().is_empty(), "summits non-empty");
    // narrowPeak is 10 columns, summits is 5
    let npline = np.lines().next().unwrap();
    assert_eq!(npline.split('\t').count(), 10, "narrowPeak is BED6+4");
    let sbline = sb.lines().next().unwrap();
    assert_eq!(sbline.split('\t').count(), 5, "summits is BED5");

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn a_valid_choice_flag_is_accepted_by_the_derived_parser() {
    // F126: the matrix stores choices comma-separated; the parser must accept a
    // genuine member like `BED` rather than rejecting it.
    let dir = tmpdir("choice");
    let (treat, _ctrl) = write_fixture(&dir);
    let argv: Vec<String> = ["-t", treat.to_str().unwrap(), "-f", "BED"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert!(
        parse_flags("callpeak", &argv).is_ok(),
        "`-f BED` is a valid choice"
    );
    let bad: Vec<String> = ["-t", treat.to_str().unwrap(), "-f", "NOPE"]
        .iter()
        .map(|s| s.to_string())
        .collect();
    assert!(
        parse_flags("callpeak", &bad).is_err(),
        "`-f NOPE` is rejected"
    );
    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn missing_required_flags_are_usage_errors() {
    // no -t
    assert!(parse_flags("callpeak", &["-g".into(), "1000".into()]).is_err());
    // bad choice rejected with a usage error
    let e = parse_flags(
        "callpeak",
        &["-t".into(), "x".into(), "-f".into(), "ZZZ".into()],
    )
    .expect_err("bad choice");
    assert!(format!("{e}").contains("invalid choice"), "got: {e}");
}

#[test]
fn help_short_circuits_required_validation() {
    // argparse prints usage and exits 0 for --help even though -t/-g are required.
    let o = parse_flags("callpeak", &["--help".into()]).expect("--help parses");
    assert!(o.help, "help flag set");
    // ...but a real invocation without the required flags is still a usage error
    assert!(parse_flags("callpeak", &["-g".into(), "1000".into()]).is_err());
}

// ---------------------------------------------------------------------------
// Rejection paths: exit 1, no output file, no panic (F27, F172)
// ---------------------------------------------------------------------------

/// `check_names` (`callpeak_cmd.py:32`, F27): treatment and control that share no
/// chromosome name at all are rejected *before* anything is written.
///
/// Upstream reaches its `sys.exit()` via an unhandled `TypeError` on the third
/// diagnostic line, so the recorded status is 1. The two readable lines are
/// reproduced verbatim; the traceback is not (see `crates/macs-cli/src/error.rs`).
#[test]
fn no_common_chromosomes_is_rejected_before_any_output_file_exists() {
    let dir = tmpdir("nochrom");
    let treat = dir.join("treat.bed");
    let ctrl = dir.join("ctrl.bed");
    std::fs::write(
        &treat,
        "chrA\t100\t200\tr\t0\t+\nchrA\t300\t400\tr\t0\t-\nchrA\t500\t600\tr\t0\t+\n",
    )
    .unwrap();
    std::fs::write(
        &ctrl,
        "chrZ\t100\t200\tr\t0\t+\nchrZ\t300\t400\tr\t0\t-\nchrZ\t500\t600\tr\t0\t+\n",
    )
    .unwrap();
    let out = dir.join("out");
    let o = parse(&[
        "-t",
        treat.to_str().unwrap(),
        "-c",
        ctrl.to_str().unwrap(),
        "-f",
        "BED",
        "-g",
        "100000",
        "--nomodel",
        "--extsize",
        "200",
        "--outdir",
        out.to_str().unwrap(),
        "-n",
        "t1",
    ]);
    let err = macs_cli::commands::callpeak::run(&o).expect_err("must be rejected");
    let msg = err.to_string();
    assert!(
        msg.starts_with("No common chromosome names can be found"),
        "unexpected diagnostic: {msg}"
    );
    assert!(
        !msg.contains("TypeError") && !msg.contains("Traceback"),
        "the Python crash site must not leak into the diagnostic: {msg}"
    );
    assert!(
        !out.exists() || std::fs::read_dir(&out).unwrap().next().is_none(),
        "no output file may be created on a rejected invocation"
    );
}

/// F172: a zero local lambda makes the p-value undefined. Upstream divides by it
/// and dies with `ZeroDivisionError` from `__call_peaks_w_control`, i.e. exit 1
/// with no output file -- not a panic, and not a silent empty result.
#[test]
fn a_zero_local_lambda_is_a_runtime_error_not_a_panic() {
    let dir = tmpdir("zerolambda");
    let treat = dir.join("treat.bed");
    let ctrl = dir.join("ctrl.bed");
    // treatment only on the contig's first contig, control only on a contig that
    // reaches it, so the shared region carries treatment reads and a lambda that
    // underflows to zero at some position
    let mut t = String::new();
    let mut c = String::new();
    for i in 0..40 {
        t.push_str(&format!("chr1\t{}\t{}\tr\t0\t+\n", 90 + i, 130 + i));
    }
    for i in 0..40 {
        c.push_str(&format!("chr1\t{}\t{}\tr\t0\t+\n", 90 + i, 130 + i));
    }
    std::fs::write(&treat, &t).unwrap();
    std::fs::write(&ctrl, &c).unwrap();
    let out = dir.join("out");
    let o = parse(&[
        "-t",
        treat.to_str().unwrap(),
        "-c",
        ctrl.to_str().unwrap(),
        "-f",
        "BED",
        "-g",
        "100000",
        "--nolambda",
        "--nomodel",
        "--extsize",
        "200",
        "--outdir",
        out.to_str().unwrap(),
        "-n",
        "t1",
    ]);
    // either outcome is acceptable here as long as it is not a panic; what this
    // test pins is that the call *returns* instead of unwinding
    match macs_cli::commands::callpeak::run(&o) {
        Ok(()) => {
            assert!(out.join("t1_peaks.xls").exists());
        }
        Err(e) => {
            let msg = e.to_string();
            assert!(
                !msg.starts_with("internal error"),
                "a rejected input must not surface as an internal error: {msg}"
            );
        }
    }
}

/// **F189** — `-p/--pvalue` selects the **p-value** scoring function.
///
/// `callpeak_cmd.py:266` dispatches on `options.log_pvalue is not None`:
/// `call_peaks(['p',], [self.log_pvalue], ...)`. This port always scored against
/// the q-value, so `-p 3` silently used `-log10(0.05)`.
#[test]
fn a_pvalue_cutoff_uses_the_pvalue_track_and_its_own_score_column() {
    let dir = tmpdir("pvalue");
    let (treat, ctrl) = write_fixture(&dir);
    let run = |args: &[&str], tag: &str| -> (String, String) {
        let out = dir.join(tag);
        let mut argv: Vec<&str> = vec![
            "-t",
            treat.to_str().unwrap(),
            "-c",
            ctrl.to_str().unwrap(),
            "-f",
            "BED",
            "-g",
            "100000",
            "--nomodel",
            "--extsize",
            "200",
            "--outdir",
            out.to_str().unwrap(),
            "-n",
            "t1",
        ];
        argv.extend_from_slice(args);
        let o = parse(&argv);
        macs_cli::commands::callpeak::run(&o).expect("callpeak runs");
        (
            std::fs::read_to_string(out.join("t1_peaks.xls")).expect("xls"),
            std::fs::read_to_string(out.join("t1_peaks.narrowPeak")).expect("narrowPeak"),
        )
    };

    let (xls_q, np_q) = run(&[], "q");
    let (xls_p, np_p) = run(&["-p", "3"], "p");

    // the header records which cutoff was used
    assert!(xls_q.contains("# qvalue cutoff = 5.00e-02"));
    // the header echoes the cutoff as given, i.e. `-log10(p)`
    assert!(xls_p.contains("# pvalue cutoff = 3.00e+00"));
    assert!(xls_p.contains("qvalue will not be calculated"));

    // The criterion really is the p-value track. `-p` takes the **natural** p
    // value and `OptValidator` turns it into `log_pvalue = -log10(pvalue)`, so
    // `-p 1e-40` is a cutoff of 40 on the `-log10(p)` scale -- past this
    // fixture's maximum -- and must call nothing, while `-q 0.05` calls peaks.
    // (`-p 1e6` is the degenerate end: its cutoff is -6, which everything passes,
    // and upstream behaves the same way.)
    let peaks_of = |s: &str| s.lines().filter(|l| l.starts_with("chr1")).count();
    let (xls_impossible, _) = run(&["-p", "1e-40"], "impossible");
    assert!(
        peaks_of(&xls_q) > 0,
        "the default -q 0.05 must call at least one peak"
    );
    assert_eq!(
        peaks_of(&xls_impossible),
        0,
        "-p 1e-40 is a cutoff of 40 on the -log10 scale, so nothing may be called"
    );

    // F189: the BED score column is `int(10 * pscore)` under `-p` and
    // `int(10 * qscore)` otherwise. The XLS q column is the same either way,
    // because `call_peaks` builds the p->q table before dispatching.
    let col5 = |np: &str| -> i64 {
        np.lines()
            .find(|l| l.starts_with("chr1"))
            .expect("a peak")
            .split('\t')
            .nth(4)
            .expect("score column")
            .parse()
            .expect("integer score")
    };
    let xls_qcol = |s: &str| -> f64 {
        s.lines()
            .find(|l| l.starts_with("chr1"))
            .expect("a peak")
            .split('\t')
            .nth(8)
            .expect("q column")
            .parse()
            .expect("float q")
    };
    let xls_pcol = |s: &str| -> f64 {
        s.lines()
            .find(|l| l.starts_with("chr1"))
            .expect("a peak")
            .split('\t')
            .nth(6)
            .expect("p column")
            .parse()
            .expect("float p")
    };
    assert_eq!(col5(&np_p), (10.0 * xls_pcol(&xls_p)) as i64);
    assert_eq!(col5(&np_q), (10.0 * xls_qcol(&xls_q)) as i64);
}
