//! `--version` must name both this port and the MACS3 release it targets.
//!
//! `TARGET_VERSION` ("3.0.5") is part of the byte-compatibility surface --
//! upstream writes it into its own output headers, so it must not drift with the
//! crate version. But a release binary that prints only `macs3-rs 3.0.5` reads
//! as a mislabelled build, and a user reporting "your version numbers are wrong"
//! is a support burden this project cannot afford on a drop-in tool. Both numbers
//! belong on the line.

use std::process::Command;

fn bin() -> std::path::PathBuf {
    // The integration-test binary lives next to the CLI binary under target/<profile>/deps.
    let mut p = std::env::current_exe().expect("test exe path");
    p.pop();
    if p.ends_with("deps") {
        p.pop();
    }
    p.join("macs3-rs")
}

fn version_line() -> String {
    let out = Command::new(bin())
        .arg("--version")
        .output()
        .expect("run macs3-rs --version");
    assert!(out.status.success(), "--version exited {:?}", out.status);
    String::from_utf8(out.stdout)
        .expect("--version is utf-8")
        .trim()
        .to_string()
}

#[test]
fn version_reports_the_port_version_and_the_compatibility_target() {
    let line = version_line();
    let crate_version = env!("CARGO_PKG_VERSION");
    assert!(
        line.contains(crate_version),
        "--version must report this crate's version ({crate_version}), got {line:?}"
    );
    assert!(
        line.contains(macs_cli::TARGET_VERSION),
        "--version must report the MACS3 compatibility target ({}), got {line:?}",
        macs_cli::TARGET_VERSION
    );
}

#[test]
fn version_starts_with_the_program_name() {
    let line = version_line();
    assert!(
        line.starts_with(macs_cli::PROGRAM),
        "--version must start with {:?}, got {line:?}",
        macs_cli::PROGRAM
    );
}

#[test]
fn target_version_is_not_the_crate_version() {
    // Guards the trap this test exists for: if someone "fixes" --version by
    // swapping in TARGET_VERSION, or makes TARGET_VERSION track CARGO_PKG_VERSION,
    // the byte-compat surface silently changes. Upstream writes 3.0.5 into
    // `# This file is generated by MACS version 3.0.5`.
    assert_eq!(
        macs_cli::TARGET_VERSION,
        "3.0.5",
        "TARGET_VERSION is written into output headers and must track upstream, \
         not this crate"
    );
    assert_ne!(
        macs_cli::VERSION,
        macs_cli::TARGET_VERSION,
        "if these are equal, --version cannot distinguish the port from the target"
    );
}
