//! Record-level parity for duplicate filtering against upstream MACS3 3.0.5.
//!
//! `track_vectors.tsv` is generated by `oracle/gen_track_vectors.py`, which drives
//! upstream's own `FWTrack.filter_dup` / `PETrack.filter_dup` over randomly
//! generated tracks. Each row records the reported total and every retained
//! position, so a divergence is localised to a position rather than to a count.
//!
//! The cases include the shapes where upstream's implementation has quirks:
//! a strand holding exactly one position, `maxnum` of 0 and of -1, fragments
//! sharing a start but differing in end, and chromosomes with a single record.

use macs_core::Strand;
use macs_track::{
    filter_frag_dup, FragTrackBuilder, Fragment, FragmentTrack, SingleEndTrack,
    SingleEndTrackBuilder,
};

/// `chrom:strand:pos` for single-end rows.
fn parse_se_kept(field: &str) -> Vec<(String, u64, Strand)> {
    if field.is_empty() {
        return Vec::new();
    }
    field
        .split(';')
        .filter(|s| !s.is_empty())
        .map(|entry| {
            let mut it = entry.split(':');
            let chrom = it.next().expect("chrom").to_string();
            let strand = match it.next().expect("strand") {
                "+" => Strand::Plus,
                "-" => Strand::Minus,
                other => panic!("bad strand {other:?} in {entry:?}"),
            };
            let pos: u64 = it.next().expect("pos").parse().expect("numeric pos");
            (chrom, pos, strand)
        })
        .collect()
}

/// `chrom:start-end` for paired-end rows.
///
/// The count of fields, not their shape, decides which parser a row uses — a
/// paired-end row has no strand, so dispatching on the row `kind` and passing the
/// right column set is the only way to avoid reading a fragment span as a strand.
fn parse_pe_kept(field: &str) -> Vec<(String, Fragment)> {
    if field.is_empty() {
        return Vec::new();
    }
    field
        .split(';')
        .filter(|s| !s.is_empty())
        .map(|entry| {
            let (chrom, span) = entry.split_once(':').expect("chrom:span");
            let (l, r) = span.split_once('-').expect("l-r");
            (
                chrom.to_string(),
                Fragment {
                    start: l.parse().expect("l"),
                    end: r.parse().expect("r"),
                },
            )
        })
        .collect()
}

/// Retained single-end positions, rendered the way the vector file does.
fn se_kept(track: &SingleEndTrack) -> Vec<String> {
    let mut out = Vec::new();
    let p = track.positions();
    for chrom in p.chroms() {
        let name = p.genome().name_string(chrom);
        for (strand, tag) in [(Strand::Plus, '+'), (Strand::Minus, '-')] {
            for pos in p.strand(chrom, strand) {
                out.push(format!("{name}:{tag}:{pos}"));
            }
        }
    }
    out
}

fn pe_kept(track: &FragmentTrack) -> Vec<String> {
    let mut out = Vec::new();
    for chrom in track.genome().ids_file_order() {
        let name = track.genome().name_string(chrom);
        for f in track.frags(chrom) {
            out.push(format!("{name}:{}-{}", f.start, f.end));
        }
    }
    out
}

#[test]
fn filter_dup_matches_upstream_on_every_vector() {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/track_vectors.tsv");
    let text = std::fs::read_to_string(path).expect("track_vectors.tsv");

    let mut se_checked = 0usize;
    let mut pe_checked = 0usize;
    let mut se_sample_checked = 0usize;
    let mut failures: Vec<String> = Vec::new();

    for (lineno, line) in text.lines().enumerate().skip(1) {
        if line.is_empty() {
            continue;
        }
        let f: Vec<&str> = line.split('\t').collect();
        assert!(f.len() >= 6, "row {lineno} has {} fields", f.len());
        // sampling rows carry three extra columns (pre-call total and the two
        // per-strand survivor counts)

        let (kind, arg1, arg2) = (f[0], f[1], f[2]);
        let is_sampling = matches!(kind, "se_sample" | "se_sample_num");

        if is_sampling {
            // columns are: kind, arg1 (percent or size), arg2 (seed), total, orig, kept
            // sampling rows: kind, arg1, seed, before, reported, plus, minus,
            // orig, kept
            let seed: i64 = arg2.parse().expect("seed");
            let before: u64 = f[3].parse().expect("before");
            let want_total: u64 = f[4].parse().expect("total");
            let want_plus: usize = f[5].parse().expect("plus");
            let want_minus: usize = f[6].parse().expect("minus");
            let orig = parse_se_kept(f[7]);
            let want = parse_se_kept(f[8]);
            debug_assert!(orig
                .iter()
                .all(|(_, _, st)| *st == Strand::Plus || *st == Strand::Minus));

            let mut b = SingleEndTrackBuilder::new();
            for (c, pos, st) in &orig {
                b.push(c.as_bytes(), *pos, *st);
            }
            b.finalize();
            let mut t = b.build();
            // the reconstructed input must match the oracle's own pre-call total,
            // otherwise the case being compared is not the case that was generated
            assert_eq!(t.total(), before, "row {lineno}: reconstructed input total");

            let got_total = if kind == "se_sample" {
                let percent: f64 = arg1.parse().expect("percent");
                macs_track::sample_percent(&mut t, percent, seed).expect("sample_percent")
            } else {
                let size: u64 = arg1.parse().expect("samplesize");
                macs_track::sample_num(&mut t, size, seed).expect("sample_num")
            };
            if got_total != want_total {
                failures.push(format!(
                    "row {lineno} {kind} arg1={arg1} seed={seed}: total {got_total}, \
                     oracle {want_total}"
                ));
                continue;
            }
            let g = t.positions();
            let got_plus: usize = g
                .chroms()
                .iter()
                .map(|c| g.strand(*c, Strand::Plus).len())
                .sum();
            let got_minus: usize = g
                .chroms()
                .iter()
                .map(|c| g.strand(*c, Strand::Minus).len())
                .sum();
            if got_plus != want_plus || got_minus != want_minus {
                failures.push(format!(
                    "row {lineno} {kind} arg1={arg1} seed={seed}: per-strand survivors \
                     +{got_plus}/-{got_minus}, oracle +{want_plus}/-{want_minus}"
                ));
            }
            let got: Vec<String> = se_kept(&t);
            let want_rendered: Vec<String> = want
                .iter()
                .map(|(c, p, st)| {
                    format!("{c}:{}:{p}", if *st == Strand::Minus { '-' } else { '+' })
                })
                .collect();
            if got != want_rendered {
                let first = got
                    .iter()
                    .zip(want_rendered.iter())
                    .position(|(a, b2)| a != b2)
                    .unwrap_or(got.len().min(want_rendered.len()));
                failures.push(format!(
                    "row {lineno} {kind} arg1={arg1} seed={seed}: retained set differs at \
                     index {first} (got {}, oracle {}); got {:?} vs oracle {:?}",
                    got.len(),
                    want_rendered.len(),
                    got.get(first),
                    want_rendered.get(first)
                ));
            }
            se_sample_checked += 1;
            continue;
        }
        // the input is recorded alongside the retained output, because
        // `filter_dup` mutates in place and the output alone cannot rebuild it
        let (orig_s, kept_s) = (f[4], f[5]);

        if kind == "se" {
            // columns are: kind, maxnum, before, reported, orig, kept
            let maxnum: i64 = arg1.parse().expect("maxnum");
            let before: u64 = arg2.parse().expect("before");
            let reported: u64 = f[3].parse().expect("reported");
            let kept = parse_se_kept(kept_s);
            // Rebuild from the recorded input. The vector is emitted grouped by
            // chromosome, plus before minus, ascending within each strand -- the
            // order the track already has after `finalize` -- so re-sorting is
            // idempotent and does not mask an ordering difference.
            let orig = parse_se_kept(orig_s);
            let mut b = SingleEndTrackBuilder::new();
            for (c, pos, st) in &orig {
                b.push(c.as_bytes(), *pos, *st);
            }
            b.finalize();
            let mut t = b.build();
            assert_eq!(t.total(), before, "row {lineno}: reconstructed total");
            let got = t.filter_dup(maxnum).expect("filter_dup");
            if got != reported {
                failures.push(format!(
                    "row {lineno} se maxnum={maxnum}: reported {got}, oracle {reported}"
                ));
                continue;
            }
            let got_kept = se_kept(&t);
            let want: Vec<String> = kept
                .iter()
                .map(|(c, p, st)| {
                    format!("{c}:{}:{p}", if *st == Strand::Minus { '-' } else { '+' })
                })
                .collect();
            if got_kept != want {
                let first = got_kept
                    .iter()
                    .zip(want.iter())
                    .position(|(a, b2)| a != b2)
                    .unwrap_or(got_kept.len().min(want.len()));
                failures.push(format!(
                    "row {lineno} se maxnum={maxnum}: kept differs at index {first} \
                     (got {}/{} entries, oracle {}/{}); got {:?} vs oracle {:?}",
                    got_kept.len(),
                    want.len(),
                    got_kept.len(),
                    want.len(),
                    got_kept.get(first),
                    want.get(first)
                ));
            }
            se_checked += 1;
        } else if kind == "pe" {
            let maxnum: i64 = arg1.parse().expect("maxnum");
            let before: u64 = arg2.parse().expect("before");
            let reported: u64 = f[3].parse().expect("reported");
            let kept = parse_pe_kept(kept_s);
            let orig = parse_pe_kept(orig_s);
            let mut b = FragTrackBuilder::new();
            for (c, f) in &orig {
                b.push(c.as_bytes(), f.start, f.end);
            }
            b.finalize();
            let mut t = b.build();
            assert_eq!(t.total(), before, "row {lineno}: reconstructed total");
            let got = filter_frag_dup(&mut t, maxnum).expect("filter_frag_dup");
            if got != reported {
                failures.push(format!(
                    "row {lineno} pe maxnum={maxnum}: reported {got}, oracle {reported}"
                ));
                continue;
            }
            let got_kept = pe_kept(&t);
            let want: Vec<String> = kept
                .iter()
                .map(|(c, f)| format!("{c}:{}-{}", f.start, f.end))
                .collect();
            if got_kept != want {
                let first = got_kept
                    .iter()
                    .zip(want.iter())
                    .position(|(a, b2)| a != b2)
                    .unwrap_or(got_kept.len().min(want.len()));
                failures.push(format!(
                    "row {lineno} pe maxnum={maxnum}: kept differs at index {first} \
                     (got {} entries, oracle {}); got {:?} vs oracle {:?}",
                    got_kept.len(),
                    want.len(),
                    got_kept.get(first),
                    want.get(first)
                ));
            }
            pe_checked += 1;
        } else {
            panic!("row {lineno}: unknown kind {kind}");
        }
    }

    assert!(
        se_checked > 200,
        "only {se_checked} single-end vectors checked"
    );
    assert!(
        pe_checked > 150,
        "only {pe_checked} paired-end vectors checked"
    );
    assert!(
        failures.is_empty(),
        "{} of {} vectors differ:\n  {}",
        failures.len(),
        se_checked + pe_checked + se_sample_checked,
        failures
            .iter()
            .take(10)
            .cloned()
            .collect::<Vec<_>>()
            .join("\n  ")
    );
}

#[test]
fn a_single_strand_element_is_retained_but_uncounted() {
    // F: upstream's `if len(plus) <= 1` branch skips the total update, so
    // `total` after filtering can be smaller than the number of positions held
    let mut b = SingleEndTrackBuilder::new();
    b.push(b"chr1", 10, Strand::Plus);
    b.push(b"chr1", 10, Strand::Plus);
    b.push(b"chr1", 99, Strand::Minus);
    b.finalize();
    let mut t = b.build();
    assert_eq!(t.filter_dup(1).unwrap(), 1);
    assert_eq!(se_kept(&t), vec!["chr1:+:10", "chr1:-:99"]);
}
